### ISSUE TITLE
RDPScreenshot Bug

### ISSUE THREAD

**Issue by ChrisTruncer** [citronneur/rdpy#13]
Hi there again!

I'm trying to go through and test your latest commits before I push out my stuff (finally), and I am running into a bug when trying to screenshot a rdp server.

I removed the IP address, but if you need one, let me know and I can send you one privately to test against.  Here is the crash dump - http://pastebin.com/PtcytEsw

Thanks!

**Comment by ChrisTruncer** [comment]
In case it helps, I also wanted to add, that the script does save an image to disk, but it is completely black picture.

**Comment by citronneur** [comment]
Hi!
TRy the last commit on hotfix branch, sorry for this bug i would like to add test for screenshot script!

Sylvain

**Comment by ChrisTruncer** [comment]
That fixed it!

Perfect!  Thanks!

**Comment by citronneur** [comment]
with pleasure
