### ISSUE TITLE
Exception when starting RDP client on os x 10.9 

### ISSUE THREAD

**Issue by ojosdegris** [citronneur/rdpy#20]
Followed installation instructions. 

on 

     rdpy-rdpclient.py server-name

Rdp window opens and I have a popup with this text:

     Lost connection : [Failure instance: Traceback (failure with no frames): 
     <class 'twisted.internet.error.ConnectionDone'>: Connection was closed cleanly. ]

And here is what I have in terminal:

    INFO : failed to auto detect keyboard layout [Errno 2] No such file or directory
    INFO : keyboard layout set to en
    INFO : *******************************************
    INFO : *          NLA Security selected          *
    INFO : *******************************************
    ^[[A2015-03-13 11:48:59.010 Python[52516:d07] modalSession has been exited 
    prematurely - check for a reentrant call to endModalSession:

pyqt installed via homebrew (brew install qt sip pyqt)

I did not expected it to work on os x 10.9 as you don't mentioned os x at all, but it was worth checking out. If it would've work for me, that going to be my replacement for CoRD as I cannot make changes to that, and contributing to python source code is actually an option. 

Thank you for this project!

**Comment by ojosdegris** [comment]
In case I provide all parameters
   
      rdpy-rdpclient.py -u **** -d **** -p **** -r log.txt server-ip

It worked on os x 10.9 

![screen shot 2015-03-13 at 12 04 07 pm](https://cloud.githubusercontent.com/assets/579795/6642179/2593d1a6-c979-11e4-8efb-40168bd24b89.png)

**Comment by citronneur** [comment]
Hello,
Try to precise domain username and password.
This is a bug because NLA want credentials to work. i need to add something to precise security layer in client.

in rdpy-rdpclient.py change line 118 self._security = rdp.SecurityLevel.RDP_LEVEL_NLA -> self._security = rdp.SecurityLevel.RDP_LEVEL_SSL

I will fixed it in next hotfix.

Sylvain

**Comment by citronneur** [comment]
thanks!

**Comment by ojosdegris** [comment]
Thanks. What is interesting, RDP clients opens and i it works fine so far, but i still has the same popup with error in the background.
