### ISSUE TITLE
ERROR : INFO PDU : Unknown code 0x0L

### ISSUE THREAD

**Issue by ciberx** [citronneur/rdpy#26]
When connecting to win server 2008 r2, i see error 
ERROR : INFO PDU : Unknown code 0x0L
but connection is correctly end. What does it mean?

**Comment by citronneur** [comment]
Sorry but rdp protocol have an error message that said all ks right. Kt’s just an artefact of protocll. I will add a if code to handle this message in next release.

Sylvain

**Comment by citronneur** [comment]
Release 1.3.1
