### ISSUE TITLE
Credentials data

### ISSUE THREAD

**Issue by ciberx** [citronneur/rdpy#27]
Hi, is it possible to get credentials data from the .rss files, or by mitmproxy programmatically?

**Comment by citronneur** [comment]
Hi,

it's depends on credential modes. When creds are specified at connection time, yes normally rss handle these informations. But if user specified his creds afetr connection only a keylogger can do the job. Normally keylogger is planned to be added in next release. I keep this bug open until it.

Sylvain

**Comment by citronneur** [comment]
Base in release 1.3.1
