### ISSUE TITLE
rdpy-rdphoneypot

### ISSUE THREAD

**Issue by ciberx** [citronneur/rdpy#29]
When i'm using Recorded Session Scenario to replay - artifacts are appear. Example screen attached.
![test](https://cloud.githubusercontent.com/assets/11668525/7321591/c84474de-eaab-11e4-9b7f-d5246765b92d.jpg)

**Comment by citronneur** [comment]
What kind of client do you use?

**Comment by ciberx** [comment]
Windows 7 standard rdp client. Rdpy work on Ubuntu server.

**Comment by citronneur** [comment]
HI,
I can't repoduce it sorry. Do you have the last version of rdpy?

**Comment by citronneur** [comment]
Fix on 1.3.2
