### ISSUE TITLE
Focus on window after alt+tab

### ISSUE THREAD

**Issue by ex0dus-cpp** [citronneur/rdpy#32]
I opened notepad and minimize it. Next, I run script rdpy and logon to the system, introduced alt + tab, then several keys through sendKeyEventUnicode. Then I come in again through the normal login. It turns out that window becomes active, but keys is not pressed (so with rdpy script letters are still introduced into the old window). So problem is that we need to wait until window will be in focus.
Another thing (that's my actually problem): I run a console with "win + r", then I want to enter a command. But the window "Run" out of focus. So all my further keys go wrong.

**Comment by citronneur** [comment]
Hi,

Sorry but RDP protocol is just base image protocol. We don't have event from application hosted on server. Protocol doesn't have means to knows number of windows, name of windows, focus or any kind of GUI events.

Sylvain

**Comment by citronneur** [comment]
Or simulate a click or tab...

**Comment by ex0dus-cpp** [comment]
Yes, i know that. But if i press "win+r" on a system (without rdp), then "run window" is on focus automatically. And if i try to press "win+r" in mstsc, or on freerdp (https://github.com/FreeRDP/FreeRDP), then "run window" on focus automatically too.
In rdpy even if i send "win+r" scancodes and wait 10 secs by time.sleep(10), focus still not set.

**Comment by ex0dus-cpp** [comment]
Please, try this code on qt4.RDPClientQt in binary rdpy-rdpclient.py. Thanks in advance.
`def sendMultiKeys(self, keys):
        extf = lambda k: (k % 256, k >= 256)
        codes = [extf(x) for x in keys]
        for k, e in codes:
            self._controller.sendKeyEventScancode(k, True, e)
        for k, e in codes[::-1]:
            self._controller.sendKeyEventScancode(k, False, e)

    def onSessionReady(self):
        """
        @summary: Windows session is ready
        @see: rdp.RDPClientObserver.onSessionReady
        """
        self.sendMultiKeys([347, 19])
        self._controller.sendKeyEventUnicode(ord(unicode('a', encoding="UTF-8")), True)
        self.sendMultiKeys([28])`
