### ISSUE TITLE
rdpy-rdpserver ?

### ISSUE THREAD

**Issue by quentinhardy** [citronneur/rdpy#35]
Hello, 

In your opinion, is it possible to have a python RDP server (rdpy-rdpserver) thanks to this project?

The aim would be to use this project client side and server side in order to don't use RDP inherent in Windows.

Thank you in advance for your response,

**Comment by citronneur** [comment]
Hi,

Good question and very hard to answer easily.
Either you add a layer on RDP with mitm or vnc server or you bind to windows graphic updates but it's not easy. The first solution maybe the easier I think.

Best regards.

Sylvain
