### ISSUE TITLE
Support for older versions of RDP (Windows XP, Server 2003, etc.)

### ISSUE THREAD

**Issue by ChrisTruncer** [citronneur/rdpy#8]
I'd love to see rdpy have support for older versions of RDP.  When I go on assessments, I still see a large number of Windows XP and Server 2003 in the networks.  It would be awesome and really helpful if rdpy was able to add support for this older version.

Thanks

**Comment by citronneur** [comment]
Done in 1.2.0 version.
Be carefull on screenshot scripts. RDP need reconnection after nego (yes poor protocol ;-)). I change a little the screenshot script to easy integrate in your project. The main function return state (maybe error) at the end for each request.

Another idea is if you find a server which only accept standard security, it's very vulnerable to Man in the middle attack!

Enjoy!
