### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by t3chn0m4g3** [citronneur/rdpy#91]
Are you planning on upgrading tp Python 3.x?

**Comment by citronneur** [comment]
yes it's planned...

**Comment by t3chn0m4g3** [comment]
Thank you for the swift feedback!

**Comment by ShayNehmad** [comment]
I'd love for this too as I have a project (Infection Monkey) which uses this and I need to migrate it to Python 3. If any help can be provided @citronneur let me know!

**Comment by Gurulhu** [comment]
if there's any ongoing project on python3 port already, I would like to help too, @citronneur

**Comment by rhertzog** [comment]
Hi, just pointing out we (Kali) would like to see a Python 3 and Qt 5 version, at least for the benefit of eyewitness which depends on rdpy. Python 2 EOL is at the end of the year, so Linux distributions (like Debian Testing on which Kali is based) are actively removing Python 2 and we need to follow that move. Do you have any idea when you will be able to tackle this ? Maybe you can jump on the help offers of @ShayNehmad and @Gurulhu 

This is tracked here on the Kali side: https://gitlab.com/kalilinux/packages/python-rdpy/issues/1

Thank you for maintaining rdpy ! Greetings from a fellow French developer ;)

**Comment by ShayNehmad** [comment]
@rhertzog We've decided to remove rdpy as a dependency from our project completely so unfortunately I'll have to withdraw my offer.

**Comment by ChrisTruncer** [comment]
Figured I would chime in and see if there's an idea of a timeline for this being updated to python3. I just upgraded EyeWitness to Py 3 and would love to get this functionality added back in again!

Thanks for all your work on this project!

**Comment by quentinhardy** [comment]
Thank you for this project.
Very interested too for having _rdpy_ compatible with python 3.
Thank you in advance.

**Comment by t3chn0m4g3** [comment]
@citronneur Any updates on Py3.x support?

**Comment by zevlag** [comment]
There is a fork someone started working on here with a Python 3 and QT 5 port.  It's currently non functioning, but a good start. https://github.com/hackdefendr/rdpy

**Comment by hackdefendr** [comment]
Thanks for the mention!

I could really use some help :) I'm having trouble with debugging and finding time to work on it.

It does install all the requirements successfully. I'm still trying to figure it all out.

**Comment by serialenabler** [comment]
yep python 3 would be super helpful. having an issue getting this installed with python 2.x :(

**Comment by citronneur** [comment]
I’m working on. See python3 branch 🏗️

**Comment by 0xbart** [comment]
Any update @citronneur ? :-)

**Comment by t3chn0m4g3** [comment]
@citronneur The Python 3 branch builds properly, however it is failing at runtime. As described [here](https://github.com/telekom-security/tpotce/issues/817) by the end of the year Alpine 3.11 will no longer receive (security) updates. We would love to continue to include RDPY in the future and hope you have the time to release a Python 3 port.
Even if not; thank you for all the time and effort you put in RDPY, it is a great addition to T-Pot and people really value it.

**Comment by citronneur** [comment]
Hello @t3chn0m4g3,

Still working on it. Need to have more times.

**Comment by t3chn0m4g3** [comment]
Thank you. I know exactly what you mean 😇

**Comment by citronneur** [comment]
🙏

**Comment by t3chn0m4g3** [comment]
For the time being I will be removing RDPY from the next T-Pot release until there is a Py3 version available.
Thanks again, RDPY is the perfect RDP honeypot.

**Comment by this-is-dimpi** [comment]
@citronneur  Are you planning on upgrading RDPY with Python 3.x? May I know please? I am trying another modules but not working effectively. It would be great help.

**Comment by sskras** [comment]
I found a fork dedicated to porting to Py 3:
https://github.com/massimiliano-dalcero/rdpy

But it looks only a bit newer than the upstream – I see only older fixes here: https://github.com/citronneur/rdpy/compare/master...massimiliano-dalcero:rdpy:master
